Attempted to capture bad lines in error file

diff --git a/containers/marax-adapter/timestamp-line b/containers/marax-adapter/timestamp-line
--- a/containers/marax-adapter/timestamp-line
+++ b/containers/marax-adapter/timestamp-line
@@ -6,5 +6,7 @@
 while read LINE; do
   if echo "$LINE" | grep -Eq "C\d{1}\.\d{2},\d{3},\d{3},\d{3},\d{4},\d{1}"; then
     echo "$(date +%s),$LINE";
+  else
+    echo "Regex failed for line [$LINE]" >&2
   fi
 done
